#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TopMedicalNews.Android.Resource", IsApplication=true)]

namespace TopMedicalNews.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::TopMedicalNews.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::TopMedicalNews.Android.Resource.String.Hello;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahBarColor = global::TopMedicalNews.Android.Resource.Attribute.ahBarColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahBarLength = global::TopMedicalNews.Android.Resource.Attribute.ahBarLength;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahBarWidth = global::TopMedicalNews.Android.Resource.Attribute.ahBarWidth;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahCircleColor = global::TopMedicalNews.Android.Resource.Attribute.ahCircleColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahDelayMillis = global::TopMedicalNews.Android.Resource.Attribute.ahDelayMillis;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahRadius = global::TopMedicalNews.Android.Resource.Attribute.ahRadius;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahRimColor = global::TopMedicalNews.Android.Resource.Attribute.ahRimColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahRimWidth = global::TopMedicalNews.Android.Resource.Attribute.ahRimWidth;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahSpinSpeed = global::TopMedicalNews.Android.Resource.Attribute.ahSpinSpeed;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahText = global::TopMedicalNews.Android.Resource.Attribute.ahText;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahTextColor = global::TopMedicalNews.Android.Resource.Attribute.ahTextColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahTextSize = global::TopMedicalNews.Android.Resource.Attribute.ahTextSize;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Drawable.ic_errorstatus = global::TopMedicalNews.Android.Resource.Drawable.ic_errorstatus;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Drawable.ic_successstatus = global::TopMedicalNews.Android.Resource.Drawable.ic_successstatus;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Drawable.roundedbg = global::TopMedicalNews.Android.Resource.Drawable.roundedbg;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Drawable.roundedbgdark = global::TopMedicalNews.Android.Resource.Drawable.roundedbgdark;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Id.loadingImage = global::TopMedicalNews.Android.Resource.Id.loadingImage;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Id.loadingProgressBar = global::TopMedicalNews.Android.Resource.Id.loadingProgressBar;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Id.loadingProgressWheel = global::TopMedicalNews.Android.Resource.Id.loadingProgressWheel;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Id.textViewStatus = global::TopMedicalNews.Android.Resource.Id.textViewStatus;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Layout.loading = global::TopMedicalNews.Android.Resource.Layout.loading;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Layout.loadingimage = global::TopMedicalNews.Android.Resource.Layout.loadingimage;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Layout.loadingprogress = global::TopMedicalNews.Android.Resource.Layout.loadingprogress;
			global::Acr.XamForms.UserDialogs.Droid.Resource.String.ApplicationName = global::TopMedicalNews.Android.Resource.String.ApplicationName;
			global::Acr.XamForms.UserDialogs.Droid.Resource.String.Hello = global::TopMedicalNews.Android.Resource.String.Hello;
			global::Acr.XamForms.UserDialogs.Droid.Resource.String.library_name = global::TopMedicalNews.Android.Resource.String.library_name;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarColor = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahBarColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarLength = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahBarLength;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarWidth = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahCircleColor = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRadius = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahRadius;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRimColor = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahRimColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRimWidth = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahText = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahText;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahTextColor = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahTextColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahTextSize = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahTextSize;
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::TopMedicalNews.Android.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::TopMedicalNews.Android.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::TopMedicalNews.Android.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::TopMedicalNews.Android.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::TopMedicalNews.Android.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::TopMedicalNews.Android.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::TopMedicalNews.Android.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::TopMedicalNews.Android.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::TopMedicalNews.Android.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::TopMedicalNews.Android.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::TopMedicalNews.Android.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::TopMedicalNews.Android.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::TopMedicalNews.Android.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::TopMedicalNews.Android.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::TopMedicalNews.Android.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::TopMedicalNews.Android.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::TopMedicalNews.Android.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::TopMedicalNews.Android.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::TopMedicalNews.Android.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::TopMedicalNews.Android.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::TopMedicalNews.Android.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::TopMedicalNews.Android.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::TopMedicalNews.Android.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::TopMedicalNews.Android.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::TopMedicalNews.Android.Resource.Styleable.ProgressWheel_ahTextSize;
			global::XLabs.Forms.Resource.Color.calendar_active_month_bg = global::TopMedicalNews.Android.Resource.Color.calendar_active_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_bg = global::TopMedicalNews.Android.Resource.Color.calendar_bg;
			global::XLabs.Forms.Resource.Color.calendar_divider = global::TopMedicalNews.Android.Resource.Color.calendar_divider;
			global::XLabs.Forms.Resource.Color.calendar_highlighted_day_bg = global::TopMedicalNews.Android.Resource.Color.calendar_highlighted_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_inactive_month_bg = global::TopMedicalNews.Android.Resource.Color.calendar_inactive_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_day_bg = global::TopMedicalNews.Android.Resource.Color.calendar_selected_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_range_bg = global::TopMedicalNews.Android.Resource.Color.calendar_selected_range_bg;
			global::XLabs.Forms.Resource.Color.calendar_text_active = global::TopMedicalNews.Android.Resource.Color.calendar_text_active;
			global::XLabs.Forms.Resource.Color.calendar_text_inactive = global::TopMedicalNews.Android.Resource.Color.calendar_text_inactive;
			global::XLabs.Forms.Resource.Color.calendar_text_selected = global::TopMedicalNews.Android.Resource.Color.calendar_text_selected;
			global::XLabs.Forms.Resource.Color.calendar_text_selector = global::TopMedicalNews.Android.Resource.Color.calendar_text_selector;
			global::XLabs.Forms.Resource.Color.calendar_text_unselectable = global::TopMedicalNews.Android.Resource.Color.calendar_text_unselectable;
			global::XLabs.Forms.Resource.Dimension.calendar_day_headers_paddingbottom = global::TopMedicalNews.Android.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::XLabs.Forms.Resource.Dimension.calendar_month_title_bottommargin = global::TopMedicalNews.Android.Resource.Dimension.calendar_month_title_bottommargin;
			global::XLabs.Forms.Resource.Dimension.calendar_month_topmargin = global::TopMedicalNews.Android.Resource.Dimension.calendar_month_topmargin;
			global::XLabs.Forms.Resource.Dimension.calendar_text_medium = global::TopMedicalNews.Android.Resource.Dimension.calendar_text_medium;
			global::XLabs.Forms.Resource.Dimension.calendar_text_small = global::TopMedicalNews.Android.Resource.Dimension.calendar_text_small;
			global::XLabs.Forms.Resource.Drawable.ad16 = global::TopMedicalNews.Android.Resource.Drawable.ad16;
			global::XLabs.Forms.Resource.Drawable.calendar_bg_selector = global::TopMedicalNews.Android.Resource.Drawable.calendar_bg_selector;
			global::XLabs.Forms.Resource.Id.calendar_grid = global::TopMedicalNews.Android.Resource.Id.calendar_grid;
			global::XLabs.Forms.Resource.Id.calendar_view = global::TopMedicalNews.Android.Resource.Id.calendar_view;
			global::XLabs.Forms.Resource.Id.left_arrow = global::TopMedicalNews.Android.Resource.Id.left_arrow;
			global::XLabs.Forms.Resource.Id.right_arrow = global::TopMedicalNews.Android.Resource.Id.right_arrow;
			global::XLabs.Forms.Resource.Id.title = global::TopMedicalNews.Android.Resource.Id.title;
			global::XLabs.Forms.Resource.Layout.calendar_pager_layout = global::TopMedicalNews.Android.Resource.Layout.calendar_pager_layout;
			global::XLabs.Forms.Resource.Layout.calendar_picker = global::TopMedicalNews.Android.Resource.Layout.calendar_picker;
			global::XLabs.Forms.Resource.Layout.dialog = global::TopMedicalNews.Android.Resource.Layout.dialog;
			global::XLabs.Forms.Resource.Layout.month = global::TopMedicalNews.Android.Resource.Layout.month;
			global::XLabs.Forms.Resource.Layout.week = global::TopMedicalNews.Android.Resource.Layout.week;
			global::XLabs.Forms.Resource.String.ApplicationName = global::TopMedicalNews.Android.Resource.String.ApplicationName;
			global::XLabs.Forms.Resource.String.Hello = global::TopMedicalNews.Android.Resource.String.Hello;
			global::XLabs.Forms.Resource.String.day_name_format = global::TopMedicalNews.Android.Resource.String.day_name_format;
			global::XLabs.Forms.Resource.String.full_date_format = global::TopMedicalNews.Android.Resource.String.full_date_format;
			global::XLabs.Forms.Resource.String.invalid_date = global::TopMedicalNews.Android.Resource.String.invalid_date;
			global::XLabs.Forms.Resource.String.library_name = global::TopMedicalNews.Android.Resource.String.library_name;
			global::XLabs.Forms.Resource.String.month_name_format = global::TopMedicalNews.Android.Resource.String.month_name_format;
			global::XLabs.Forms.Resource.Style.CalendarCell = global::TopMedicalNews.Android.Resource.Style.CalendarCell;
			global::XLabs.Forms.Resource.Style.CalendarCell_CalendarDate = global::TopMedicalNews.Android.Resource.Style.CalendarCell_CalendarDate;
			global::XLabs.Forms.Resource.Style.CalendarCell_DayHeader = global::TopMedicalNews.Android.Resource.Style.CalendarCell_DayHeader;
			global::XLabs.Forms.Resource.Style.CalendarTitle = global::TopMedicalNews.Android.Resource.Style.CalendarTitle;
			global::XLabs.Platform.Resource.String.ApplicationName = global::TopMedicalNews.Android.Resource.String.ApplicationName;
			global::XLabs.Platform.Resource.String.Hello = global::TopMedicalNews.Android.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int down_to_up = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int up_to_down = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int calendar_active_month_bg = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int calendar_bg = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int calendar_divider = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int calendar_highlighted_day_bg = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int calendar_inactive_month_bg = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int calendar_selected_day_bg = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int calendar_selected_range_bg = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int calendar_text_active = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int calendar_text_inactive = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int calendar_text_selected = 2131230729;
			
			// aapt resource value: 0x7f080011
			public const int calendar_text_selector = 2131230737;
			
			// aapt resource value: 0x7f08000a
			public const int calendar_text_unselectable = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int xam_blue = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int xam_dark_blue = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int xam_gray = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int xam_green = 2131230734;
			
			// aapt resource value: 0x7f080010
			public const int xam_light_gray = 2131230736;
			
			// aapt resource value: 0x7f08000b
			public const int xam_purple = 2131230731;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050002
			public const int calendar_day_headers_paddingbottom = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int calendar_month_title_bottommargin = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int calendar_month_topmargin = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int calendar_text_medium = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int calendar_text_small = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int head_view_height = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int need_refresh_delta = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ad16 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int calendar_bg_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int collection = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int collection_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int comment_btn = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int down_arrow = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_errorstatus = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_launcher = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_successstatus = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int IndicatorDown = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int IndicatorRight = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int logout_btn = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int password = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int person_center_btnx = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int pip = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int pip_selected = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int portait = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int portait_logo_bg = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int reading_btn = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int reading_collection_btn = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int return_btnx = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int roundedbg = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int roundedbgdark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int setting_btn = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int shape = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int share = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int splashscreen = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int tag_bg = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int xiala = 2130837533;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000f
			public const int calendar_grid = 2131296271;
			
			// aapt resource value: 0x7f090001
			public const int calendar_view = 2131296257;
			
			// aapt resource value: 0x7f090011
			public const int content_ly = 2131296273;
			
			// aapt resource value: 0x7f090006
			public const int foot_layout_progress = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int foot_layout_text = 2131296261;
			
			// aapt resource value: 0x7f090012
			public const int foot_ly = 2131296274;
			
			// aapt resource value: 0x7f090007
			public const int head_layout_left_arrow = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int head_layout_left_progressbar = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int head_layout_title = 2131296265;
			
			// aapt resource value: 0x7f090010
			public const int head_ly = 2131296272;
			
			// aapt resource value: 0x7f090003
			public const int left_arrow = 2131296259;
			
			// aapt resource value: 0x7f09000c
			public const int loadingImage = 2131296268;
			
			// aapt resource value: 0x7f09000a
			public const int loadingProgressBar = 2131296266;
			
			// aapt resource value: 0x7f09000d
			public const int loadingProgressWheel = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int myButton = 2131296270;
			
			// aapt resource value: 0x7f090002
			public const int right_arrow = 2131296258;
			
			// aapt resource value: 0x7f09000b
			public const int textViewStatus = 2131296267;
			
			// aapt resource value: 0x7f090000
			public const int title = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int wall_progress_ly = 2131296260;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_pager_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int calendar_picker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int foot_layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int head_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int loading = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int loadingimage = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int loadingprogress = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int month = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int pull_refresh_scroll_view = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int week = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060007
			public const int ApplicationName = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int Hello = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int day_name_format = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int full_date_format = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int hello = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int invalid_date = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int library_name = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int month_name_format = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int pull_to_refresh = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int pull_up_to_get_more = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int refreshing = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int release_to_get_more = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int release_to_refresh = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int CalendarCell = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int CalendarCell_CalendarDate = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int CalendarCell_DayHeader = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int CalendarTitle = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int MyActionBarStyle = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int MyTheme = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int MyTheme_WithActionBar = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int Theme_Splash = 2131165190;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
